language: java
before_install: ./gradlew clean
jdk:
  - oraclejdk8
services: mongodb
notifications:
  email: true
  hipchat:
    rooms:
      secure: mMFgjrSodmOm2qI71FVH/2XJ+dSP7q6LkVHgy+l7/KCfCpl6EdVdtHTEfvzKrTtN8KlQoTYmyC5HZ1X/jS0jp1xDrjMbMaqmzJk0qcBYpyMKQ9AtCG8cPeAtXrF0bnhEvY1DeYikI0PUnd6wzIqAUIEFJ6c2DAS1pQSp+qqiiASdpsqEfVeYrekiFfhRaobTz8Hdqb+DBy0j+2UoHfZ7Y2pAdHmTJvsY2EdcVBYSN4LkDY8P6dZ736Erv/130FEVy72+0fAqOdGC48Bg+3u5ygxAixnszDaoO+2v3JKhAPbUunYQ+BTyU5VKz0/0M8CMZtO3hvXg+o+rzieMBoKzOlJAn7BnCItyQv9pPEBChXHf4ET2TX89NVW6h/9QYuzl7kebd+O9E1ArLva6KTMvcPc1GWQtY/5MDiK/IbUN6nQPm6F9AOxZP6BKkdH23iG4s8byVpUWWuCUJiZtdvNMzEcD9TpMhGg4isUY8Aah/STFk/JPNbMJhG17qVguSIRF3bBiI8TsqJb7zSLYKq+awlbxoVdbP5WhI8DIG88ddi2L7b6jqHAbCYSG6kSS1Pig//98eBsyakjzt6wNYU+Noze9jq9u1S7AeS9uiW+ZELG398vXHSQNT1dhnUeHgWRyIjZGYeiTWvRZONFu6LS7X8CRmo5ffUB6Y5qCU/zzs40=
install:
  - ./gradlew clean build test jacocoTestReport
after_success:
  - mkdir -p $CIRCLE_TEST_REPORTS/junit/
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} $CIRCLE_TEST_REPORTS/junit/\;
  - find . -type f -regex ".*/build/test-results/.*" -exec cp {} $CIRCLE_TEST_REPORTS/junit/\;
  - bash <(curl -s https://codecov.io/bash)
deployment:
  staging:
    branch: master
    heroku:
      appname: kotlin-tech-board-staging