language: java
before_install: ./gradlew clean
jdk:
  - oraclejdk8
services: mongodb
notifications:
  email: true
install:
  - ./gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)